### ISSUE TITLE
Support Roon as input / play / pause

### ISSUE THREAD

**Issue by jimbo-l** [sicamois/homebridge-naim-audio#2]
Great plugin. Would it be possible to support Roon as an input, and be able to play / pause etc?

**Comment by sicamois** [comment]
Hello,

Thx for the feedback, it is really good to hear !

I checked and unfortunately Naim doesn't allow us to manage Roon via the
API. Thus, Roon cannot be treated as an input (I also checked if I could
hack my way in, but no...).
I'll keep you posted if Naim updates its firmware and allows for control of
Roon.

In the meantime, there's a Homebridge plugin for Roon (kinda the other way
around). I haven't tested it yet, so I can confirm if it fulfills all your
needs... but it's out there :
https://www.npmjs.com/package/homebridge-roon-outputs

Po

**Comment by jimbo-l** [comment]
Thanks for looking. I've seen the Roon plugin, which is OK but not quite what I was after. Maybe Naim will open up the API one day :)
